import React from "react";
import Navbar from "../components/common/Navbar";
import Footer from "../components/common/Footer";

function TermsAndConditions() {
  const sections = [
    {
      id: 1,
      title: "Introduction & Acceptance",
      content: [
        {
          text: "Welcome to BodhiBridal Matrimony (herein referred as BM). This document is an electronic record in terms of the Information Technology Act, 2000 and rules there under pertaining to electronic records as applicable and amended. This electronic record is generated by a computer system and does not require any physical or digital signatures.",
          points: [],
        },
        {
          text: "This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries Guidelines and Digital Media Ethics Code) Rules, 2021.",
          points: [],
        },
        {
          subtitle: "Important Notice",
          text: "PLEASE READ THE FOLLOWING TERMS AND CONDITIONS VERY CAREFULLY BEFORE USING THE WEBSITE/WAP/APP. ACCESSING, BROWSING OR OTHERWISE USING THE WEBSITE/WAP/APP IMPLIES YOUR AGREEMENT TO BE BOUND BY ALL THESE TERMS AND CONDITIONS. If you do not want to be bound by the Terms and Conditions, you must not use the Website or the BM Services.",
          points: [],
          highlight: true,
        },
        {
          subtitle: "Definitions",
          text: "In these Terms:",
          points: [
            '"BM member" means the end user accessing the Website/BM services, its contents or using the BM Services offered',
            '"BM member" also includes persons such as father, mother, brother, sister, relative or a friend ("Registrant") of the prospective bride/bridegroom',
            '"BM Services" means the matrimonial service provided by BodhiBridal Matrimony',
            'The terms "You" and "User" shall be interchangeably used for term "BM member"',
            'The terms "We/Our/Us" shall be used interchangeably for BodhiBridal Matrimony',
          ],
        },
      ],
    },
    {
      id: 2,
      title: "Scope",
      content: [
        {
          text: "You understand and acknowledge that BodhiBridal Matrimony (BM) acts as an 'Intermediary' as defined under clause (1) sub-clause (w) of Section 2 of the Information Technology Act, 2000.",
          points: [],
        },
        {
          text: "BM acts as a platform to enable any user to themselves register on it (by filling the mandatory fields and optional fields, if any) to voluntarily search for profile(s) from the database of BM's already registered users, for seeking prospective lawful matrimonial alliances for themselves.",
          points: [],
        },
        {
          subtitle: "Platform Services",
          text: "Our services include:",
          points: [
            "Profile creation and management",
            "Searching profiles from the database based on partner preferences",
            "Shortlisting profiles you are interested in",
            "Free/paid access for searching profiles",
            "Assistance through retail stores (with valid mobile number and email)",
          ],
        },
      ],
    },
    {
      id: 3,
      title: "Eligibility",
      content: [
        {
          subtitle: "A. BM Membership is reserved for:",
          text: "",
          points: [
            "Indian Nationals & Citizens",
            "Persons of Indian Origin (PIO)",
            "Non Resident Indians (NRI)",
            "Persons of Indian Descent or Indian Heritage",
          ],
        },
        {
          subtitle: "B. As a BM member you confirm that you are:",
          text: "",
          points: [
            "18 years or above (if you are a woman) or 21 years or above (if you are a man)",
            "If you have applied for Divorce, you may register by stating 'Awaiting Divorce'",
            "If you are a resident of any other Country, you are legally competent to marry as per the local rules applicable to your country",
            "You shall comply with the Indian laws for marrying a person of Indian Origin",
          ],
        },
        {
          subtitle: "C. Registrant Consent",
          text: "In case you are a Registrant of the prospective bride/bridegroom and has created profile on behalf of them, it implies that you have taken their consent for their profile creation and for accessing the BM Website/WAP/App.",
          points: [],
        },
      ],
    },
    {
      id: 4,
      title: "Registration",
      content: [
        {
          subtitle: "A. Registration Requirements",
          text: "We expect that you would complete the online registration process with fairness and honesty:",
          points: [
            "Furnish true, accurate, current, complete information",
            "Provide recent photos (not older than 6 months)",
            "Read relevant columns before keying in details",
            "Do not key in details in fields other than applicable fields",
            "Do not mention IDs of other platforms/websites",
            "Do not repeat details in multiple fields",
          ],
        },
        {
          subtitle: "B. False Information",
          text: "If at any point of time we come to know that any information provided by you (including photos) is found to be untrue, inaccurate, or incomplete, we shall have the full right to:",
          points: [
            "Suspend or terminate (without any notice) your BM membership",
            "Forfeit any amount paid by you towards BM membership fee",
            "Refuse to provide BM service to you thereafter",
          ],
        },
        {
          subtitle: "C. Profile Blocking",
          text: "BM reserves the right to block the registration of your profile if:",
          points: [
            "Contact details/links are entered in irrelevant fields",
            "There are errors in any data entered by members",
          ],
        },
        {
          subtitle: "D. Duplicate Profiles",
          text: "Registration of duplicate profiles of the same person is not allowed. We shall have full right to suspend or terminate (without any notice) such duplicate profile.",
          points: [],
        },
        {
          subtitle: "E. Bonafide Intention",
          text: "You acknowledge and confirm that your registration with BM and the usage of BM services is with the bonafide intention of marriage and not otherwise. BM Membership is restricted strictly to the registered BM individual member only. Organizations, companies, businesses cannot become Members of BM.",
          points: [],
        },
      ],
    },
    {
      id: 5,
      title: "Account Security",
      content: [
        {
          text: "You are responsible for safeguarding the confidentiality of your BM login credentials such as your user id, password, OTP, etc., and for restricting access to your computer/mobile to prevent unauthorized access to your account.",
          points: [],
        },
        {
          subtitle: "Security Guidelines",
          text: "",
          points: [
            "We, as a Company do not ask for Password",
            "You are cautioned not to share your password to any persons",
            "You agree to accept responsibility for all activities that occur under your account",
          ],
          highlight: true,
        },
      ],
    },
    {
      id: 6,
      title: "Role and Responsibility of BM",
      content: [
        {
          subtitle: "Our Obligations",
          text: "",
          points: [
            "BM reproduces your details once you register on 'as is' and 'as available' basis",
            "Our obligation is only to provide an interface to registered members to search prospects",
            "Profile search and matches are automatically generated based on partner preference set by you",
            "BM does not prohibit any member from sending interest to your profile",
            "We cannot guarantee or assume responsibility for specific results from the use of data",
          ],
        },
        {
          subtitle: "Security Measures",
          text: "",
          points: [
            "BM shall safeguard sensitive user information using security standards, authentication mechanisms, access controls and encryption techniques",
            "BM cannot guarantee complete protection of user data while in transit",
            "BM cannot prevent tampering of data by third party with malicious intent",
          ],
        },
        {
          subtitle: "Disclaimer",
          text: "BM does not authenticate/endorse any information of any profile. You as a user need to verify the credentials and information provided by other users.",
          points: [],
          highlight: true,
        },
      ],
    },
    {
      id: 7,
      title: "Role and Responsibility of BM Member",
      content: [
        {
          subtitle: "A. Password Security",
          text: "You shall safeguard your profile information by creating a strong password with combination of alphabets (upper and lower case) and numbers.",
          points: [],
        },
        {
          subtitle: "B. Verification",
          text: "You are requested to verify the credentials of the prospect and exercise due care regarding:",
          points: [
            "Marital status",
            "Educational qualifications",
            "Financial status",
            "Occupation",
            "Character",
            "Health status",
          ],
        },
        {
          subtitle: "C. Photo Requirements",
          text: "To get better search results, provide latest photograph which should not be more than 3 (three) months old. Providing old photographs, photographs of others, AI generated photographs, inaccurate/false information shall be treated as violation of terms and conditions.",
          points: [],
        },
        {
          subtitle: "D. BM Members are advised to refrain from:",
          text: "",
          points: [
            "Entering into any financial transactions with prospects",
            "Seeking or providing financial help from/to other BM Members",
            "Using abusive language when communicating with other members",
            "Being discriminative or using racial comments",
            "Sharing confidential and personal data including bank details",
            "Entering into physical relationship with any prospect before marriage",
            "Violating any law for the time being in force",
            "Mentioning details of other matrimonial services in personalized messages",
          ],
        },
        {
          subtitle: "E. Safety Awareness",
          text: "BM Members are expected to be cautious of prospects who:",
          points: [
            "Ask for favours, money or sexual favours",
            "Call from multiple phone numbers",
            "Only interact over phone",
            "Don't come forward for face to face meeting (physically or through video calls)",
            "Don't involve family and friends in match making",
          ],
          highlight: true,
        },
        {
          subtitle: "F. Profile Management",
          text: "",
          points: [
            "Regularly log in to the profile and send expression of interest",
            "Review expression of interest sent to you and respond suitably",
            "Update any change in particulars furnished in profile",
            "In case of finalization of marriage, delete profile or intimate us for removal",
          ],
        },
        {
          subtitle: "G. Prohibited Activities",
          text: "BM member shall NOT:",
          points: [
            "Use any kind of Bots like web robots, Chatbot or automated processes",
            "Probe, scan or test vulnerabilities of the BM Website/App",
            "Breach security measures instituted by BM",
            "Make any payment to account of any BM employees (all payments to BM account only)",
            "Air grievances/complaints in social media (approach BM to resolve)",
          ],
        },
      ],
    },
    {
      id: 8,
      title: "Customer Care / Customer Service",
      content: [
        {
          text: "In the event you come across any concerns in our service, please contact us:",
          points: [],
        },
        {
          subtitle: "Contact Details",
          text: "",
          points: [
            "Email ID: helpdesk@bodhibridal.com",
            "Contact No: +91-XXXXXXXXXX",
            "Address: BodhiBridal Matrimony, [Your Address], [City, State - PIN]",
          ],
        },
      ],
    },
    {
      id: 9,
      title: "Medium of Communication",
      content: [
        {
          subtitle: "A. Communication Consent",
          text: "BM member hereby consents for receiving communication including promotional communications through:",
          points: [
            "Electronic mails",
            "Calls",
            "SMS",
            "WhatsApp messages",
          ],
        },
        {
          subtitle: "B. DND Confirmation",
          text: "BM member confirms that the mobile number submitted is not registered with Do Not Disturb / National Customer Preference Register. If registered, calls from BM shall not be treated as promotional calls.",
          points: [],
        },
        {
          subtitle: "C. Communication Frequency",
          text: "You are entitled to set up your communications frequency from us, like only on weekends or fortnightly. You may also opt for not getting any call from us by ticking the appropriate box in the Website/WAP/App.",
          points: [],
        },
      ],
    },
    {
      id: 10,
      title: "Confidentiality",
      content: [
        {
          text: "Any feedback you provide to us shall be deemed to be non-confidential. We shall be free to use such feedback/information on an unrestricted basis.",
          points: [],
        },
        {
          subtitle: "By submitting feedback, you represent and warrant that:",
          text: "",
          points: [
            "Your feedback does not contain confidential or proprietary information of yourself or third parties",
            "BM member is not under any obligation of confidentiality with respect to the feedback",
            "You are not entitled to any compensation or reimbursement from us for the feedback",
          ],
        },
      ],
    },
    {
      id: 11,
      title: "Privacy of Membership",
      content: [
        {
          text: "To protect your privacy and understand our practices, please read and follow our Privacy Policy which also governs your visit to BM. The personal information/data provided to us by you during usage will be treated as confidential and in accordance with the Privacy Policy and applicable laws.",
          points: [],
        },
        {
          subtitle: "Important",
          text: "If you object to your information being transferred or used, please do not use the website.",
          points: [],
          highlight: true,
        },
      ],
    },
    {
      id: 12,
      title: "Grievance Officer",
      content: [
        {
          text: "In the event you come across any violation by another user including but not limited to content that is obscene, menacing, grossly offensive, harming minors, infringing copyright, patents, or another user is impersonating, please contact:",
          points: [],
        },
        {
          subtitle: "Grievance Officer Details",
          text: "",
          points: [
            "Email: grievanceofficer@bodhibridal.com",
            "Grievance Officer: Mr. [Officer Name]",
            "Address: BodhiBridal Matrimony, [Your Address], [City, State - PIN]",
          ],
        },
        {
          subtitle: "Availability",
          text: "The Grievance Officer shall be available between 10 AM till 6 PM IST from Monday to Saturday excluding Sunday and public holidays in India.",
          points: [],
        },
        {
          subtitle: "Prohibited Content",
          text: "The Grievance Officer handles complaints related to content that:",
          points: [
            "Belongs to another person without rights",
            "Is obscene, pornographic, paedophilic, invasive of privacy",
            "Is insulting or harassing on basis of gender, race, ethnicity",
            "Is harmful to child",
            "Infringes any patent, trademark, copyright",
            "Deceives or misleads about origin of message",
            "Impersonates another person",
            "Threatens unity, integrity, defence, security or sovereignty of India",
            "Contains software virus or malicious code",
            "Violates any law for the time being in force",
          ],
        },
      ],
    },
    {
      id: 13,
      title: "Disputes Between Members",
      content: [
        {
          subtitle: "A. Member Responsibility",
          text: "BM Members are solely responsible for communications with prospects. We expressly disclaim any responsibility or liability for:",
          points: [
            "Monetary transactions between members",
            "Exchange of information between members",
            "Interactions via email, chat, WhatsApp or any other medium",
          ],
        },
        {
          subtitle: "B. No Obligation to Monitor",
          text: "BM has no obligation to monitor any disputes arising between members. We shall not be party to any such dispute/litigation.",
          points: [],
        },
        {
          subtitle: "C. Not a Broker",
          text: "We are not a broker or agent of any BM member. BM does not partake in exchange of any discussion between members or results of their discussion.",
          points: [],
        },
      ],
    },
    {
      id: 14,
      title: "Content Rights",
      content: [
        {
          subtitle: "I. BM Content",
          text: "You agree that all content of BM belongs to BodhiBridal Matrimony excluding your or third party content.",
          points: [],
        },
        {
          subtitle: "II. Your Content",
          text: "You acknowledge that you alone are responsible and liable for:",
          points: [
            "Profile details and photographs",
            "Content keyed in at the time of profile creation",
            "All posts and communications with other members",
            "Personalized messages sent to other members",
          ],
        },
        {
          subtitle: "III. License Grant",
          text: "By submitting content to BM, you grant us a worldwide, non-exclusive, royalty-free, sub-licensable and transferable license to use, reproduce, distribute, display, publish, and communicate your content.",
          points: [],
        },
        {
          subtitle: "IV. Content Removal",
          text: "If content is found not in compliance with Terms and Conditions, BM may delete the content and/or terminate or suspend your registration without refund.",
          points: [],
        },
      ],
    },
    {
      id: 15,
      title: "Third Party Websites",
      content: [
        {
          subtitle: "A. Third Party Advertisements",
          text: "We may allow third parties to put up advertisements on the BM application/Website. We do not control the contents of such third party advertisements. Third party websites are governed by their own terms and conditions.",
          points: [],
        },
        {
          subtitle: "B. Third Party Services",
          text: "We may also allow third parties to provide services like horoscope matching on the website/App. We may collect payment for such services. In no event shall we be liable to you for such third party services.",
          points: [],
        },
        {
          subtitle: "C. Service Modifications",
          text: "BM reserves the right to add/delete/alter/modify/suspend any or all the BM Services at any time without notice.",
          points: [],
        },
      ],
    },
    {
      id: 16,
      title: "Limitation of Liability",
      content: [
        {
          subtitle: "A. No Liability",
          text: "BM shall under no circumstances be liable or responsible for any:",
          points: [
            "Direct, indirect, special, exemplary, incidental, or consequential damages",
            "Damages resulting from the use of Website/WAP/App/Third Party Website/BM services",
          ],
        },
        {
          subtitle: "B. No Guarantee",
          text: "Exchange of profiles through BM should not be construed as a matrimonial offer and/or recommendation and/or advice or guarantee.",
          points: [],
        },
        {
          subtitle: "C. Maximum Liability",
          text: "Our liability to you for any cause whatsoever will at all times be limited to the amount paid by you to BM for any specific paid package, and no further.",
          points: [],
        },
        {
          subtitle: "D. Additional Exclusions",
          text: "BM shall NOT be liable for:",
          points: [
            "Wrong/improper match due to unavailability of profiles",
            "Financial transactions between members",
            "Members not responding/reciprocating to your approach",
          ],
        },
      ],
    },
    {
      id: 17,
      title: "Class Action Suits",
      content: [
        {
          text: "You acknowledge and confirm that you will not bring or participate in any class action or other class proceeding in connection with any dispute with us. Neither you nor BM agrees to class arbitration.",
          points: [],
          highlight: true,
        },
      ],
    },
    {
      id: 18,
      title: "General Provisions",
      content: [
        {
          subtitle: "False Complaints",
          text: "If you file a false complaint against another prospect and we suspend/delete that prospect's profile based on your complaint, we reserve our right to:",
          points: [
            "Initiate appropriate legal (Civil/Criminal) action against you",
            "Claim all costs and expenses from you",
            "Suspend your profile",
            "Forfeit any amounts paid by you",
          ],
        },
        {
          subtitle: "Content Moderation",
          text: "BM reserves the absolute right to delete any content of any profile listing to ensure proper consent, accuracy, and compliance with prevailing laws especially relating to:",
          points: [
            "Obscene, libelous, blasphemous, slanderous or defamatory content",
            "Content invasive of another person's right of privacy",
            "Harmful, vulgar, pornographic, abusive content",
            "Harassing, threatening, hateful, objectionable content",
            "Content suggesting unfair or illegal activity",
          ],
        },
        {
          subtitle: "Membership Expiry",
          text: "Once your paid membership expires:",
          points: [
            "You cannot avail unexpired balance phone call count/SMS",
            "You cannot access already viewed member contact information",
            "Unless you renew within 30 days",
            "On renewal, unexpired phone call/SMS shall be carried forward",
          ],
        },
      ],
    },
    {
      id: 19,
      title: "Disclaimer",
      content: [
        {
          subtitle: "A. As Is Basis",
          text: 'Your access to and use of the BM Services is at your own risk. THE BM SERVICES ARE PROVIDED TO YOU ON AN "AS IS" AND "AS AVAILABLE" BASIS. TO THE FULL EXTENT PERMITTED BY LAW, BM DISCLAIMS ALL WARRANTIES, EXPRESS OR IMPLIED, OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR NON-INFRINGEMENT.',
          points: [],
          highlight: true,
        },
        {
          subtitle: "B. No Guarantee of Marriage",
          text: "We do not give any implied or explicit guarantee or warranty of marriage or alliance by you choosing to register on our Website/App.",
          points: [],
        },
        {
          subtitle: "C. No Responsibility For:",
          text: "",
          points: [
            "Any act or omission by payment gateway/alliance partners",
            "Untrue or incorrect information submitted by any member",
            "Decisions taken based on information provided by other users",
            "Unauthorized or illegal acts by third parties",
            "Cybercrime attempted or committed by anyone",
            "Incidents of force-majeure or 'act of god'",
            "Technical malfunction of telecommunication networks",
            "Software, hardware failures, network congestion",
            "Outcome of interactions in meetings, calls, SMS, chat, email",
          ],
        },
        {
          subtitle: "D. Device Damage",
          text: "We are not liable for any damage or alteration to your equipment including computer equipment, hand-held devices or mobile telephones as a result of installation or use of the App.",
          points: [],
        },
      ],
    },
    {
      id: 20,
      title: "Indemnity",
      content: [
        {
          text: "By using our BM services you agree to defend, indemnify, and hold harmless BodhiBridal Matrimony, its subsidiaries, affiliates, Directors, officers, agents, partners and employees from any loss, damage, liability, claim, or demand, including reasonable attorney's fees, made by any person through improper use of the service.",
          points: [],
        },
        {
          subtitle: "Important",
          text: "This defence and indemnification obligation will survive in perpetuity.",
          points: [],
          highlight: true,
        },
      ],
    },
    {
      id: 21,
      title: "Termination",
      content: [
        {
          subtitle: "A. Grounds for Termination",
          text: "BM reserves the right to terminate your membership or suspend/delete your profile if you:",
          points: [
            "Seek physical/financial favors from other registered members",
            "Provide incorrect information on website/WAP/App",
            "Commit fraudulent/unlawful/illegal activities",
            "Violate Terms and Conditions",
            "Misappropriate name, likeness, email, contact of another member",
            "Create profile by impersonation/fake/false/misrepresentation",
            "Use photos of third parties without permission",
            "Act with other members/employees in indecent/improper manner",
          ],
        },
        {
          subtitle: "B. Complaint-based Suspension",
          text: "If we receive any complaint against you and suspend/delete your profile in good faith, we shall not be liable to you in any manner whatsoever.",
          points: [],
        },
        {
          subtitle: "C. User-initiated Deactivation",
          text: "BM membership may be deactivated by you without assigning any reasons. However, all amount paid till date by you to BM shall be forfeited.",
          points: [],
        },
        {
          subtitle: "D. Effect of Termination",
          text: "Upon termination/suspension:",
          points: [
            "Your right to use or access BM Website/App services will cease immediately",
            "Disclaimers and limitations of liability shall survive termination",
            "Termination shall not relieve you of obligations arising prior to termination",
          ],
        },
      ],
    },
    {
      id: 22,
      title: "Jurisdiction and Applicable Law",
      content: [
        {
          subtitle: "A. Jurisdiction",
          text: "The registration of BM membership and all BM services are deemed to have been entered into within the territorial Jurisdiction of Chennai, India.",
          points: [],
        },
        {
          subtitle: "B. Governing Law",
          text: "BM Members unconditionally agree that all disputes shall be governed by the Laws of India and submit to the exclusive jurisdiction of appropriate court of law in Chennai, Tamil Nadu, India.",
          points: [],
        },
      ],
    },
    {
      id: 23,
      title: "Mode of Payment",
      content: [
        {
          subtitle: "A. Payment Methods",
          text: "Payment made by:",
          points: [
            "Cash",
            "Cheque",
            "Net Banking",
            "Debit/Credit Card",
            "PayPal",
            "RTGS/NEFT",
          ],
        },
        {
          text: "Payment shall be in accordance with prevailing RBI guidelines. Activation of paid BM service shall be subject to realization of said payment.",
          points: [],
        },
        {
          subtitle: "B. Cheque Dishonor",
          text: "In case of dishonor of Cheque/demand draft, you shall be liable to pay applicable bank charges. BM service will be deactivated/suspended until you settle the value.",
          points: [],
        },
        {
          subtitle: "C. Third Party Payment Gateways",
          text: "BM uses third party payment gateways for collection. You provide explicit consent to share your mobile number with authorized Payment Gateway partners for payment processing, transaction communications, and fraud prevention.",
          points: [],
        },
      ],
    },
    {
      id: 24,
      title: "Refund and Assignment",
      content: [
        {
          subtitle: "Non-Refundable",
          text: "The payments made by any BM member by way of membership/renewal fee/auto renewal are treated as non-refundable.",
          points: [],
          highlight: true,
        },
        {
          subtitle: "No Assignment",
          text: "",
          points: [
            "BM member shall not assign or transfer membership to any other person/entity",
            "Such assignment shall be treated as violation of terms and conditions",
            "Payment once made cannot be assigned to any person/party",
            "Payment cannot be adjusted towards any other product or packages",
          ],
        },
      ],
    },
    {
      id: 25,
      title: "Renewal",
      content: [
        {
          subtitle: "A. Automatic Renewal",
          text: "We automatically renew all paid Memberships before expiry. You agree that your account will be subject to this automatic renewal feature.",
          points: [],
        },
        {
          subtitle: "B. Renewal Terms",
          text: "When you first subscribe, you acknowledge that when your paid Membership expires, it will automatically renew for the duration and at the last paid price.",
          points: [],
        },
        {
          subtitle: "C. Maximum Tenure",
          text: "The maximum tenure of any packages will be 12 (Twelve) months. Every BM package post validity period shall be renewed.",
          points: [],
        },
        {
          subtitle: "D. Cancellation",
          text: "If you do not want your paid membership to automatically renew, you must cancel your paid/automatic membership by emailing to cancellation@bodhibridal.com",
          points: [],
        },
        {
          subtitle: "E. Duration Calculation",
          text: "One month is computed as '30 days'. Hence, 3 months package = 90 days, 6 months = 180 days subscription.",
          points: [],
        },
      ],
    },
    {
      id: 26,
      title: "NRI Terms (Non-Resident Indians)",
      content: [
        {
          subtitle: "A. Jurisdiction",
          text: "The laws of India shall be applicable.",
          points: [],
        },
        {
          subtitle: "B. Arbitration of Disputes",
          text: "Parties shall discuss and resolve disputes informally. If not resolved within 30 days, disputes may be resolved through individual arbitration under the Arbitration and Conciliation Act, 1996. The seat of Arbitration shall be Chennai, Tamil Nadu, India. Proceedings shall be conducted in English.",
          points: [],
        },
        {
          subtitle: "C. Intellectual Property",
          text: "Disputes relating to infringement of intellectual property rights may be resolved by means other than arbitration.",
          points: [],
        },
        {
          subtitle: "D. Renewal for NRI",
          text: "Customer is charged the current prevailing price and renewal is done only for 3 months duration irrespective of past package.",
          points: [],
        },
        {
          subtitle: "E. Enforcement",
          text: "Any proceeding to enforce this arbitration agreement may be brought in Courts of Chennai, Tamil Nadu, India.",
          points: [],
        },
      ],
    },
    {
      id: 27,
      title: "Membership Packages",
      content: [
        {
          subtitle: "A. Package Types",
          text: "We have various premium membership packages called Gold, Diamond, Platinum, Till U Marry and Assisted.",
          points: [],
        },
        {
          subtitle: "B. Package Duration",
          text: "You shall opt for any of our premium membership packages varying between three months to one year with differing price to access various premium features.",
          points: [],
        },
        {
          subtitle: "C. Contact View Limits",
          text: "Each premium package has contact view limits. Prime and Prime Platinum offer unlimited views under Fair Usage Policy (FUP). Unlimited views apply only to mutually accepted profiles where acceptance occurred during current active Prime plan.",
          points: [],
        },
        {
          subtitle: "D. Fair Usage Policy (FUP) Limits",
          text: "",
          points: [
            "Day Zero Paid Limit: PM Count 50, Phone View 20",
            "Daily Limit: PM Count 100, Phone View 30",
            "Weekly Limit: PM Count 150, Phone View 50",
            "Monthly Limit: PM Count 500, Phone View 100",
            "Total Limit: PM Count 4000, Phone View 750",
          ],
        },
      ],
    },
    {
      id: 28,
      title: "Money Back Guarantee",
      content: [
        {
          text: "If you meet the below conditions and do not find a match within 21 days, get a full refund! No questions asked!",
          points: [],
        },
        {
          subtitle: "Eligibility Conditions:",
          text: "",
          points: [
            "User must have added minimum of 3 photos to profile",
            "Profile should be Govt ID verified",
            "Profile completion score must be at least 80%",
            "User must have messaged at least 15 mutually matching profiles in first 21 days",
            "User does not have a single reply on messages initiated",
            "User should not have consumed any phone number from membership",
            "21 Day Money Back guarantee is only applicable for self serve packs",
            "Does not apply to any assisted package",
          ],
        },
      ],
    },
    {
      id: 29,
      title: "Child Safety Standards",
      content: [
        {
          subtitle: "A. Age Restriction",
          text: "Our platform is intended for use only by individuals aged 18 and older. We do not permit Children under the age of 18 to access or use our App.",
          points: [],
          highlight: true,
        },
        {
          subtitle: "B. Prohibited Content",
          text: "We prohibit posting, uploading, or sharing any content that depicts, promotes, or exploits children in any form, including child pornography or any form of sexual abuse.",
          points: [],
        },
        {
          subtitle: "C. CSAM Prevention",
          text: "We scan all user generated content to prevent illegal material including CSAM (Child Sexual Abuse Material) from being uploaded, shared or distributed. Our app takes appropriate action by removing CSAM after obtaining actual knowledge of it.",
          points: [],
        },
        {
          subtitle: "D. Violations",
          text: "Any content violating our Child Safety standard will result in immediate suspension of membership.",
          points: [],
        },
        {
          subtitle: "E. Reporting",
          text: "Users can report CSAM concerns to:",
          points: [
            "Email: reportabuse@bodhibridal.com",
            "National Cyber Crime Reporting Portal: https://cybercrime.gov.in",
          ],
        },
        {
          subtitle: "F. Compliance",
          text: "We confirm that our app complies with all applicable child safety laws and regulations.",
          points: [],
        },
      ],
    },
  ];

  return (
    <div className="min-h-screen bg-white">
      {/* Navbar */}
      <Navbar />

      {/* Hero Section */}
      <section className="bg-gradient-to-r from-orange-500 to-red-500 py-16 sm:py-20">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 md:px-8 text-center">
          <h1 className="text-3xl sm:text-4xl md:text-5xl font-bold text-white mb-4">
            Terms & Conditions
          </h1>
          <p className="text-lg sm:text-xl text-white/90 max-w-4xl mx-auto mb-4">
            Please read these terms carefully before using BodhiBridal Matrimony.
            By using our services, you agree to these terms.
          </p>
          <p className="text-sm text-white/70">Last Updated: January 2025</p>
        </div>
      </section>

      {/* Important Notice */}
      <section className="py-8 bg-red-50 border-b border-red-100">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 md:px-8">
          <div className="flex items-start gap-4 p-6 bg-white rounded-xl shadow-sm border-l-4 border-red-500">
            <span className="text-3xl">⚠️</span>
            <div>
              <h3 className="font-bold text-red-800 mb-2 text-lg">Important Notice</h3>
              <p className="text-red-700 leading-relaxed">
                BodhiBridal Matrimony is a platform that facilitates introductions between 
                individuals seeking matrimonial alliances. We do not guarantee marriage or 
                successful matches. All users are advised to conduct their own verification 
                and due diligence before proceeding with any relationship. We recommend 
                meeting in public places and informing family members before meeting anyone.
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* Main Content - Two Column Layout */}
      <section className="py-12 md:py-16">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 md:px-8">
          <div className="grid lg:grid-cols-4 gap-8">
            
            {/* Left Sidebar - Table of Contents (Sticky) */}
            <div className="lg:col-span-1">
              <div className="lg:sticky lg:top-24">
                <div className="bg-gray-50 rounded-2xl p-6 border border-gray-200 max-h-[70vh] overflow-y-auto">
                  <h3 className="text-lg font-bold text-gray-800 mb-4 flex items-center gap-2">
                    <span className="text-orange-500">📋</span> Contents
                  </h3>
                  <nav className="space-y-1">
                    {sections.map((section) => (
                      <a
                        key={section.id}
                        href={`#section-${section.id}`}
                        className="block text-xs text-gray-600 hover:text-orange-500 hover:bg-orange-50 px-3 py-2 rounded-lg transition-colors"
                      >
                        <span className="font-semibold text-orange-500 mr-1">
                          {section.id}.
                        </span>
                        {section.title.length > 25
                          ? section.title.substring(0, 25) + "..."
                          : section.title}
                      </a>
                    ))}
                  </nav>
                </div>

                {/* Quick Contact Card */}
                <div className="bg-gradient-to-br from-orange-500 to-red-500 rounded-2xl p-6 mt-6 text-white">
                  <h4 className="font-bold mb-2">Have Questions?</h4>
                  <p className="text-sm text-white/90 mb-4">
                    Contact our legal team for any concerns about our terms.
                  </p>
                  <a
                    href="mailto:legal@bodhibridal.com"
                    className="inline-block bg-white text-orange-500 font-semibold text-sm px-4 py-2 rounded-lg hover:bg-gray-100 transition-colors"
                  >
                    Contact Legal
                  </a>
                </div>
              </div>
            </div>

            {/* Right Content - Main Sections */}
            <div className="lg:col-span-3">
              {/* All Sections */}
              <div className="space-y-8">
                {sections.map((section) => (
                  <div
                    key={section.id}
                    className="bg-white rounded-2xl border border-gray-200 p-6 md:p-8 hover:shadow-lg transition-shadow"
                    id={`section-${section.id}`}
                  >
                    {/* Section Header */}
                    <div className="flex items-start gap-4 mb-6">
                      <span className="flex-shrink-0 w-12 h-12 bg-gradient-to-r from-orange-500 to-red-500 text-white rounded-xl flex items-center justify-center font-bold text-lg">
                        {section.id}
                      </span>
                      <h2 className="text-xl sm:text-2xl font-bold text-gray-800 pt-2">
                        {section.title}
                      </h2>
                    </div>

                    {/* Section Content */}
                    <div className="space-y-5">
                      {section.content.map((item, idx) => (
                        <div key={idx}>
                          {item.subtitle && (
                            <h3 className="text-base font-semibold text-gray-800 mb-2">
                              {item.subtitle}
                            </h3>
                          )}

                          {item.highlight ? (
                            <div className="bg-red-50 border-l-4 border-red-500 p-4 rounded-r-lg">
                              <p className="text-red-700 font-medium text-sm">
                                {item.text}
                              </p>
                              {item.points && item.points.length > 0 && (
                                <ul className="mt-3 space-y-2">
                                  {item.points.map((point, pointIdx) => (
                                    <li
                                      key={pointIdx}
                                      className="flex items-start gap-2 text-red-700 text-sm"
                                    >
                                      <span className="w-1.5 h-1.5 bg-red-500 rounded-full mt-2 flex-shrink-0"></span>
                                      <span>{point}</span>
                                    </li>
                                  ))}
                                </ul>
                              )}
                            </div>
                          ) : (
                            <>
                              {item.text && (
                                <p className="text-gray-600 leading-relaxed text-sm">
                                  {item.text}
                                </p>
                              )}
                              {item.points && item.points.length > 0 && (
                                <ul className="mt-3 grid sm:grid-cols-1 gap-2">
                                  {item.points.map((point, pointIdx) => (
                                    <li
                                      key={pointIdx}
                                      className="flex items-start gap-3 text-gray-600 bg-gray-50 p-3 rounded-lg text-sm"
                                    >
                                      <span className="w-2 h-2 bg-orange-500 rounded-full mt-1.5 flex-shrink-0"></span>
                                      <span>{point}</span>
                                    </li>
                                  ))}
                                </ul>
                              )}
                            </>
                          )}
                        </div>
                      ))}
                    </div>
                  </div>
                ))}
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Agreement Section */}
      <section className="py-12 md:py-16 bg-gray-50">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 md:px-8">
          <div className="bg-white p-8 md:p-10 rounded-2xl shadow-md text-center">
            <h3 className="text-2xl font-bold text-gray-800 mb-6">
              By Using BodhiBridal Matrimony, You Agree To
            </h3>
            <div className="flex flex-wrap justify-center gap-4 mb-6">
              <span className="bg-green-100 text-green-700 px-5 py-2 rounded-full text-sm font-medium flex items-center gap-2">
                <span>✅</span> These Terms & Conditions
              </span>
              <span className="bg-green-100 text-green-700 px-5 py-2 rounded-full text-sm font-medium flex items-center gap-2">
                <span>✅</span> Our Privacy Policy
              </span>
              <span className="bg-green-100 text-green-700 px-5 py-2 rounded-full text-sm font-medium flex items-center gap-2">
                <span>✅</span> Community Guidelines
              </span>
              <span className="bg-green-100 text-green-700 px-5 py-2 rounded-full text-sm font-medium flex items-center gap-2">
                <span>✅</span> Safe Matrimony Practices
              </span>
            </div>
            <p className="text-gray-600 text-sm max-w-2xl mx-auto">
              If you do not agree with any of these terms, please do not use our services. 
              Your continued use of BodhiBridal Matrimony constitutes acceptance of these terms.
            </p>
          </div>
        </div>
      </section>

      {/* Contact CTA */}
      <section className="py-12 md:py-16 bg-gradient-to-r from-orange-500 to-red-500">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 md:px-8">
          <div className="flex flex-col lg:flex-row items-center justify-between gap-8">
            <div className="text-center lg:text-left">
              <h2 className="text-2xl sm:text-3xl font-bold text-white mb-2">
                Questions About Our Terms?
              </h2>
              <p className="text-white/90">
                Our support team is here to help clarify any concerns.
              </p>
            </div>
            <div className="flex flex-col sm:flex-row gap-4">
              <a
                href="/contact"
                className="inline-block bg-white text-orange-500 font-bold py-3 px-8 rounded-lg hover:bg-gray-100 transition-colors shadow-lg text-center"
              >
                Contact Support
              </a>
              <a
                href="/privacy-policy"
                className="inline-block bg-transparent border-2 border-white text-white font-bold py-3 px-8 rounded-lg hover:bg-white hover:text-orange-500 transition-colors text-center"
              >
                View Privacy Policy
              </a>
            </div>
          </div>
        </div>
      </section>

      {/* Footer */}
      <Footer />
    </div>
  );
}

export default TermsAndConditions;